# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compute.proto

import sys

_b = (
    sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
)
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="compute.proto",
    package="",
    syntax="proto3",
    serialized_pb=_b(
        '\n\rcompute.proto",\n\x0e\x43omputeRequest\x12\x0b\n\x03num\x18\x01 \x01(\x05\x12\r\n\x05times\x18\x02 \x01(\x05\x62\x06proto3'
    ),
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_COMPUTEREQUEST = _descriptor.Descriptor(
    name="ComputeRequest",
    full_name="ComputeRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="num",
            full_name="ComputeRequest.num",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="times",
            full_name="ComputeRequest.times",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=17,
    serialized_end=61,
)

DESCRIPTOR.message_types_by_name["ComputeRequest"] = _COMPUTEREQUEST

ComputeRequest = _reflection.GeneratedProtocolMessageType(
    "ComputeRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_COMPUTEREQUEST,
        __module__="compute_pb2"
        # @@protoc_insertion_point(class_scope:ComputeRequest)
    ),
)
_sym_db.RegisterMessage(ComputeRequest)


# @@protoc_insertion_point(module_scope)
